# Generated by Django 3.2.16 on 2022-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_av_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='0', upload_to=''),
            preserve_default=False,
        ),
    ]
